### ISSUE TITLE
[Feature Request] Support the notification of E-mails.

### ISSUE THREAD

**Issue by wafer-li** [beta/homework#33]
Could it support to use email, such as Gmail, to send a notification to remind me that the deadline is  close?

**Comment by beta** [comment]
Nope, as it's only some client-side pages and scripts, and there's no daemon program to send those emails.

Later I'll find a server and rewrite it with something like Ruby or PHP. But I'm not sure if there will be email notifications or not, as I prefer mobile client apps and integration into other GTD apps better.

**Comment by wafer-li** [comment]
Okay, I see.
