### ISSUE TITLE
电子商务概论

### ISSUE THREAD

**Issue by beta** [beta/homework#45]
course: 电子商务概论
deadline: '2016-10-31'
submit: |
  直接给老师展示。

  检查时上交纸质版实验报告，不需要提交任何电子版文件。

---

一个人完成至少使用 Struts 2 做出登录并做一点其他功能，多人组队要使用 SSH 框架并开发更多的功能。

18 和 19 周课上给老师展示。

**Comment by forestbird** [comment]
秀梅
